# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

continuation_prompt = ''


format = """
$sudo($username[@](bold fg:yellow)$hostname )\
$directory \
($git_branch $git_commit ($git_state )$git_metrics$git_status)\
$c$java$lua$python$rust\
$fill\
$time
$character
"""

# format = """
# ╭──◯  $username$hostname
# ├──◯  $c$java$lua$python$rust
# ├──◯  [Directory:](bold green) $directory
# ╰──◯  $character
# """

# # Style String Options
# bold
# italic
# underline
# dimmed
# inverted  # Inverts the foreground and background colors
# blink
# hidden
# strikethrough
# bg:<color>
# fg:<color>
# <color>
# none


palette = "catppuccin-mocha"
[palettes.catppuccin-mocha]
rosewater = "#F5E0DC"
flamingo = "#F2CDCD"
pink = "#F5C2E7"
mauve = "#CBA6F7"
red = "#F38BA8"
maroon = "#EBA0AC"
peach = "#FAB387"
yellow = "#F9E2AF"
green = "#A6E3A1"
teal = "#94E2D5"
sky = "#89DCEB"
sapphire = "#74C7EC"
cyan = "#00FFFF"
blue = "#89B4FA"
darkblue = "#545AA7"
lavender = "#B4BEFE"
text = "#CDD6F4"
subtext1 = "#BAC2DE"
subtext0 = "#A6ADC8"
overlay2 = "#9399b2"
overlay1 = "#7F849C"
surface2 = "#585B70"
surface1 = "#45475A"
surface0 = "#313244"
base = "#1E1E2E"
mantle = "#181825"
crust = "#11111B"


# One line prompt
[line_break]
disabled = false

[cmd_duration]
disabled = true

[hostname]
disabled = true
ssh_only = false
format = '[$ssh_symbol$hostname](bold fg:yellow)'

[username]
disabled = true
show_always = true
format = '[$user](bold fg:yellow)'

[sudo]
disabled = false
format = '[$symbol](bold fg:blue)'
symbol = "🥷 " 

[directory]
disabled = false
home_symbol = "~"
truncate_to_repo = false
read_only = " "
format = '[$path$readonly](bold fg:cyan)'

[env_var]
disabled = true
variable = "VIRTUAL_ENV"
symbol = ""
default = ""
format = "[$env_value](bold fg:yellow)"

[git_branch]
disabled = false
symbol = ""
# symbol = ""
format = '[$symbol $branch(:$remote_branch)](bold fg:pink)'

[git_commit]
disabled = false
format = '[#$hash$tag](bold fg:pink)'
only_detached = false

[git_state]
disabled = false

[git_metrics]
disabled = false
format = '([+$added](bold fg:green) )([-$deleted](bold fg:red) )'

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]](bold fg:red) )'
conflicted = '='
ahead = '⇡'
behind = '⇣'
diverged = '⇕'
up_to_date = ''
untracked = '?'
stashed = '\$'
modified = '!'
staged = '+'
renamed = '»'
deleted = '✘'

[time]
disabled = false
format = '[$time](bold fg:yellow)'
time_format = "%b %d, %T"

[aws]
disabled = false
symbol = "  "

[c]
disabled = false
symbol = " "
format = '[\[$symbol($version(-$name))\]]($style)'

[conda]
disabled = false
symbol = " "

[docker_context]
disabled = false
symbol = " "

[golang]
disabled = false
symbol = " "

[haskell]
disabled = false
symbol = " "

[hg_branch]
disabled = false
symbol = " "

[java]
disabled = false
symbol = " "
format = '[\[$symbol$version\]]($style)'

[julia]
disabled = false
symbol = " "

[lua]
disabled = false
symbol = " "
format = '[\[$symbol$version\]]($style)'

[nodejs]
disabled = false
symbol = " "

[package]
disabled = false
symbol = " "

[python]
disabled = false
symbol = " "
format = '[\[$symbol$version(  $virtualenv)\]]($style)'

[rust]
disabled = false
symbol = " "
format = '[\[$symbol($version)\]]($style)'

[fill]
disabled = false
symbol = " "

[character]
disabled = false
format = "$symbol "
# success_symbol = "[➜](bold fg:green)"
# error_symbol = "[➜](bold fg:red)"
# vicmd_symbol = "[➜](bold fg:mauve)"
success_symbol = """
[\
╷ 
╰─◯](fg:green)"""
error_symbol = """
[\
╷ 
╰─◯](fg:red)"""
vimcmd_symbol = """
[\
╷ 
╰─◯](fg:mauve)"""
