# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

continuation_prompt = "[ ](bold fg:yellow)"


format = """
$directory \
($git_branch $git_commit ($git_state )$git_metrics$git_status)\
$c$golang$java$lua$python$rust\
$fill\
$time
($sudo$hostname$username )$character
"""


# format = """
# ([](fg:blue)($sudo )($hostname$username)[](fg:blue) )\
# [](fg:blue)$directory[](fg:blue) \
# [](fg:blue)($git_branch $git_commit ($git_state )$git_metrics$git_status)[](fg:blue)\
# $c$golang$java$lua$python$rust\
# $fill\
# $time
# $character
# """

# # Style String Options
# bold
# italic
# underline
# dimmed
# inverted  # Inverts the foreground and background colors
# blink
# hidden
# strikethrough
# bg:<color>
# fg:<color>
# <color>
# none


palette = "catppuccin-mocha"
[palettes.catppuccin-mocha]
rosewater = "#F5E0DC"
flamingo = "#F2CDCD"
pink = "#F5C2E7"
mauve = "#CBA6F7"
red = "#F38BA8"
maroon = "#EBA0AC"
peach = "#FAB387"
yellow = "#F9E2AF"
green = "#A6E3A1"
teal = "#94E2D5"
sky = "#89DCEB"
sapphire = "#74C7EC"
cyan = "#00FFFF"
blue = "#89B4FA"
darkblue = "#545AA7"
lavender = "#B4BEFE"
text = "#CDD6F4"
subtext1 = "#BAC2DE"
subtext0 = "#A6ADC8"
overlay2 = "#9399b2"
overlay1 = "#7F849C"
surface2 = "#585B70"
surface1 = "#45475A"
surface0 = "#313244"
base = "#1E1E2E"
mantle = "#181825"
crust = "#11111B"


# One line prompt
[line_break]
disabled = false

[cmd_duration]
disabled = true

[hostname]
disabled = false
ssh_only = false
ssh_symbol = " "
style = "bold bg:base fg:blue"
format = '[$ssh_symbol$hostname@]($style)'

[username]
disabled = false
show_always = true
style_root = "bold bg:base fg:red"
style_user = "bold bg:base fg:blue"
format = '[$user]($style)'

[sudo]
disabled = false
symbol = "🥷" 
style = "bold bg:base"
format = '[$symbol]($style)'

[directory]
disabled = false
home_symbol = "~"
truncate_to_repo = false
read_only = " "
style = "bold bg:base fg:yellow"
format = '[$path$readonly]($style)'

[env_var]
disabled = true
variable = "VIRTUAL_ENV"
symbol = ""
default = ""
style = "bold fg:text"
format = "[$env_value]($style)"

[git_branch]
disabled = false
symbol = ""
# symbol = ""
style = "bold bg:base fg:pink"
format = '[$symbol $branch(:$remote_branch)]($style)'

[git_commit]
disabled = false
only_detached = false
tag_disabled = false
tag_symbol = "  🏷 "
style = "bold bg:base fg:pink"
format = '[#$hash$tag]($style)'

[git_state]
disabled = false

[git_metrics]
disabled = false
added_style = "bold bg:base fg:green"
deleted_style = "bold bg:base fg:red"
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'

[git_status]
disabled = false
conflicted = '='
ahead = '⇡'
behind = '⇣'
diverged = '⇕'
up_to_date = ''
untracked = '?'
stashed = '\$'
modified = '!'
staged = '+'
renamed = '»'
deleted = '✘'
style = "bold bg:base fg:red"
format = '([\[$all_status$ahead_behind\]]($style) )'

[time]
disabled = false
time_format = "%b %d, %T"
style = "bold fg:yellow"
format = '[$time]($style)'

[aws]
disabled = false
symbol = "  "

[c]
disabled = false
# detect_extensions = ['c', 'h', 'cpp', 'hpp']
symbol = " "
format = '[\[$symbol($version(-$name))\]]($style)'

[conda]
disabled = false
symbol = " "

[docker_context]
disabled = false
symbol = " "

[golang]
disabled = false
symbol = " "
format = '[\[$symbol$version\]]($style)'

[haskell]
disabled = false
symbol = " "

[hg_branch]
disabled = false
symbol = " "

[java]
disabled = false
symbol = " "
format = '[\[$symbol$version\]]($style)'

[julia]
disabled = false
symbol = " "

[lua]
disabled = false
symbol = " "
format = '[\[$symbol$version\]]($style)'

[nodejs]
disabled = false
symbol = " "

[package]
disabled = false
symbol = " "

[python]
disabled = false
symbol = " "
format = '[\[$symbol$version(  $virtualenv)\]]($style)'

[rust]
disabled = false
symbol = " "
format = '[\[$symbol($version)\]]($style)'

[fill]
disabled = false
symbol = " "

[character]
disabled = false
success_symbol = "[➜](bold fg:green)"
error_symbol = "[➜](bold fg:red)"
vicmd_symbol = "[➜](bold fg:mauve)"
# success_symbol = """
# [\
# ╷ 
# ╰─◯](fg:green)"""
# error_symbol = """
# [\
# ╷ 
# ╰─◯](fg:red)"""
# vimcmd_symbol = """
# [\
# ╷ 
# ╰─◯](fg:mauve)"""
format = "$symbol "
