# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

continuation_prompt = ''

format = """
$hostname\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$lua\
$line_break\
$character
"""

right_format = """
$time
"""

# One line prompt
[line_break]
disabled = false

[cmd_duration]
disabled = true


[hostname]
ssh_only = false
format = '\[[$ssh_symbol$hostname]($style)\] '
disabled = true

[username]
show_always = false
format = '[\[$user\]](bold #00ffff) '

[directory]
truncate_to_repo = false
format = '[$path](#00ffff)[$read_only]($read_only_style) '

[character]
success_symbol = "[➜](bold #50fa7b)"
error_symbol = "[➜](bold #50fa7b)" 
vimcmd_symbol = "[](bold #50fa7b)"
vimcmd_visual_symbol = "[](bold #f0fa8b)"

[python]
disabled = false
format = '[$symbol$version]($style)'
[lua]
disabled = false
format = '[$symbol$version]($style)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_commit]
format = '[#$hash$tag]($style) '
only_detached = false
disabled = false

[git_state]

[git_metrics]
disabled = false

[git_status]

[time]
format = '[\[$time\]](bold #00ffff)'
disabled = false
