# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

continuation_prompt = ''

# format = """
# ╭─◯ $username$hostname
# ├─◯ $c$java$lua$python$rust
# ├─◯ [Directory:](bold green) $directory
# ╰─◯ $character
# """

format = """
$directory$git_branch$git_commit$git_state$git_metrics$git_status$c$java$lua$python$rust$env_var
$character
"""

right_format = """
$time
"""

# One line prompt
[line_break]
disabled = true

[cmd_duration]
disabled = true

[hostname]
disabled = false
ssh_only = false
format = '[$ssh_symbol$hostname](bold #F9E2AF)'

[username]
disabled = false
show_always = true
format = '[$user](bold #F9E2AF)'

[directory]
disabled = false
home_symbol = "~"
truncate_to_repo = false
read_only = " "
format = '[$path](#00FFFF)[$read_only]($read_only_style) '

[character]
disabled = false
success_symbol = "[➜](bold #A6DA95)"
error_symbol = "[➜](bold #ED8796)" 
vimcmd_symbol = "[](bold #C6A0F6)"
vimcmd_visual_symbol = "[](bold #C6A0F6)"

[env_var]
disabled = true
variable = "VIRTUAL_ENV"
symbol = ""
default = ""
format = "[$env_value](bold #EED49F)"

[git_branch]
disabled = false
symbol = ""
format = '[\[$symbol $branch(:$remote_branch)\]]($style) '

[git_commit]
disabled = false
format = '[\[#$hash$tag\]]($style) '
only_detached = false

[git_state]
disabled = false

[git_metrics]
disabled = false
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = '='
ahead = '⇡'
behind = '⇣'
diverged = '⇕'
up_to_date = ''
untracked = '?'
stashed = '\$'
modified = '!'
staged = '+'
renamed = '»'
deleted = '✘'

[time]
disabled = false
format = '[\[$time\]](bold #00ffff)'

[aws]
disabled = false
symbol = "  "

[c]
disabled = false
symbol = " "
format = '[\[$symbol($version(-$name))\]]($style)'

[conda]
disabled = false
symbol = " "

[docker_context]
disabled = false
symbol = " "

[golang]
disabled = false
symbol = " "

[haskell]
disabled = false
symbol = " "

[hg_branch]
disabled = false
symbol = " "

[java]
disabled = false
symbol = " "
format = '[\[$symbol$version\]]($style)'

[julia]
disabled = false
symbol = " "

[lua]
disabled = false
symbol = " "
format = '[\[$symbol$version\]]($style)'

[nodejs]
disabled = false
symbol = " "

[package]
disabled = false
symbol = " "

[python]
disabled = false
symbol = " "
format = '[\[$symbol$version(  $virtualenv)\]]($style)'

[rust]
disabled = false
symbol = " "
format = '[\[$symbol($version)\]]($style)'
