# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

continuation_prompt = ''

format = """
$hostname\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$lua\
$java\
$env_var\
$line_break\
$character
"""

right_format = """
$time
"""

# One line prompt
[line_break]
disabled = false

[cmd_duration]
disabled = true

[hostname]
ssh_only = false
format = '\[[$ssh_symbol$hostname]($style)\] '
disabled = true

[username]
show_always = false
format = '[\[$user\]](bold #00FFFF) '

[directory]
truncate_to_repo = false
read_only = " "
format = '[$path](#00FFFF)[$read_only]($read_only_style) '

[character]
success_symbol = "[➜](bold #A6DA95)"
error_symbol = "[➜](bold #ED8796)" 
vimcmd_symbol = "[](bold #C6A0F6)"
vimcmd_visual_symbol = "[](bold #C6A0F6)"

[env_var]
disabled = true
variable = "VIRTUAL_ENV"
symbol = ""
default = ""
format = "[$env_value](bold #EED49F)"

[git_branch]
symbol = ""
format = '[\[$symbol $branch(:$remote_branch)\]]($style) '

[git_commit]
disabled = false
format = '[\[#$hash$tag\]]($style) '
only_detached = false

[git_state]
disabled = false

[git_metrics]
disabled = false
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = '='
ahead = '⇡'
behind = '⇣'
diverged = '⇕'
up_to_date = ''
untracked = '?'
stashed = '$'
modified = '!'
staged = '+'
renamed = '»'
deleted = '✘'

[time]
format = '[\[$time\]](bold #00ffff)'
disabled = false

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "
format = '[\[$symbol$version\]]($style)'

[julia]
symbol = " "

[lua]
symbol = " "
format = '[\[$symbol$version\]]($style)'

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "
format = '[\[$symbol$version(  $virtualenv)\]]($style)'

[spack]
symbol = "🅢 "

[rust]
symbol = " "
